### PR TITLE
Add IPGlasma as an initial condition module

### PR DESCRIPTION
**Pull request by chunshen1987**
I added IPGlasma as an initial condition module. It provides the system's energy-momentum tensor to hydrodynamics and initial binary collision points for hard processes.

A simplified Glasma module is added as a dummy pre-equilibrium module to connect IPGlasma and MUSIC.

I provide an example jetscape_user_IPGlasmaMUSIC.xml in the config/ folder to perform test runs for this mode.

### CODE REVIEW

**Comment by chunshen1987** [comment]
@jdmulligan @amitkr2410 Please take a look at the PbPb test. I don't know which part of the update breaks the regression test. Thanks!

**Comment by amitkr2410** [comment]
Hi @chunshen1987, 
I have tested the IPGlasma branch. I don't see any issue (pp and PbPb runs) on my local machine. I am attaching here output files for the following XML file (https://github.com/jdmulligan/JETSCAPE-analysis/blob/master/test/PbPb/output/latest/0_Q01.0_recoil_on0_broadening_on0_qhat0-2.0/jetscape_user.xml) with <nEvents> set to 1. 
(1) test_out_IPGlasma_public_branch.dat  : This is from IPGlasma branch                                          
(2) test_out_master_public_branch.dat : This is from master branch
[test_out_IPGlasma_public_branch.txt](https://github.com/JETSCAPE/JETSCAPE/files/6617898/test_out_IPGlasma_public_branch.txt)
[test_out_master_public_branch.txt](https://github.com/JETSCAPE/JETSCAPE/files/6617899/test_out_master_public_branch.txt)

The PbPb regression test fails because the x,y location generated in PythiaHard scattering module are different even though a constant (identical) seed has been used in both the JETSACPE runs. The changes in PythiaGun can be seen here: https://github.com/JETSCAPE/JETSCAPE/pull/89/files#diff-57cfbf5f9f2075658060a32d0d549d2ed10c203d5e5bfc5f011dac4c6e111377
For uniformity, the assignment of x,y location of the parton has been moved to the InitiaState module of the framework:
https://github.com/JETSCAPE/JETSCAPE/pull/89/files#diff-2bb76bb8b18e2aa398ec97ceddaa29d937d4ebd69b5cf710c9e479194d01076e
I'm not sure how the sequence of random numbers would change as the function is "SampleABinaryCollisionPoint()" is only called from PythiaGun.cc!

**Comment by chunshen1987** [comment]
Hi @amitkr2410,

If you set the binary production point to the one sampled in the master branch, would the final result be the same as the ones in the automatic test? Thanks!

**Comment by jdmulligan** [comment]
Automated tests were now updated (thanks @latessa!) and pass.
I added a dummy commit to re-trigger the tests, since for some reason the button to re-run them disappeared for this PR.

Merging now to 3.4-rc branch.

**Pull request merged**
