### PR TITLE
Hadron printer

### PR DESCRIPTION
**Pull request by bardelch**
This hadron printer is merged into the Jetscape 3.0 framework.

### CODE REVIEW

**Comment by amajumder** [comment]
@jdmulligan, are you ok with this pull request?

**Comment by jdmulligan** [comment]
@bardelch can you make a PR to master if this is ready for review? Otherwise it is not obvious what the changes are -- also the automatic tests don't run.

**Comment by amajumder** [comment]
There is an active pull request and I see that you (James) are one of the
reviewers.
Abhijit

**Comment by jdmulligan** [comment]
The current PR is to merge into a separate branch -- not master. You can go ahead and do that anytime, if you want to keep developing on that branch -- no need for a careful review, that can wait until merging to master. Otherwise, if you want to merge this into master, the PR should be directed there.

**Comment by amajumder** [comment]
Chuck can you move the PR into master.

**Pull request merged**
