### PR TITLE
Writer for final state partons and hadrons

### PR DESCRIPTION
**Pull request by raymondEhlers**
This adds a JetScape writer for final state partons and hadrons. This way, you can write final state * without having to write the full output. I performed validation with the header v2 comparing the new writer vs the FinalState* executables in the example, and the values seem to be within an absolute tolerance of 1e-3 and relative tolerance of 5e-5. I interpret this as basically our precision limit.

Also introduces a new final state hadrons and partons ascii format, known as header v2, with contains:
- additional event information
- the cross section and error stored in the same file
- more consistent spacing for parsing
- removed eta and phi to reduce storage size (since we already have the full kinematics)

A full comparison of the header v2 format is below:

# FinalStateHadrons

## Original header

Invoked with:`./FinalStateHadrons input_ascii_file.dat final_state_hadrons.dat`
```
#   0.0116446   Event1ID    236 pstat-EPx   Py  Pz  Eta Phi
0 -211 0 2.18047 0.236423 0.673826 -2.05549 -1.77929 1.23335
1 211 0 8.62818 -0.698026 0.851136 -8.55659 -2.74796 2.25768
```
(with tabs as ">" for clarity):
```
#>0.0116446>Event1ID>236>pstat-EPx>Py>Pz>Eta>Phi
```

## Header v2

Invoked with:`./FinalStateHadrons input_ascii_file.dat final_state_hadrons.dat true`
```
#   Event   1   weight  0.129547    EPangle 0.0116446   N_hadrons   236 |   N   pid status  E   Px  Py  Pz  Eta Phi
0 -211 0 2.18047 0.236423 0.673826 -2.05549 -1.77929 1.23335
1 211 0 8.62818 -0.698026 0.851136 -8.55659 -2.74796 2.25768
```
(with tabs as ">" for clarity):
```
#>Event>1>weight>0.129547>EPangle>0.0116446>N_hadrons>236>|>N>pid>status>E>Px>Py>Pz>Eta>Phi
```

# FinalStatePartons

## Original header

Invoked with:`./FinalStateHadrons input_ascii_file.dat final_state_hadrons.dat`
```
#   0.0116446   Event1ID    183 pstat-EPx   Py  Pz  Eta Phi
0   21  -1  0.332548    0.289347    -0.13353    -0.0950621  -0.294051   5.85082
1   21  1   4.45215 1.15158 -0.518765   -4.26926    -1.93227    5.85993
```
(with tabs as ">" for clarity):
```
#>0.0116446>Event1ID>183>pstat-EPx>Py>Pz>Eta>Phi
```

## Header v2

Invoked with:`./FinalStateHadrons input_ascii_file.dat final_state_hadrons.dat true`
```
#   Event   1   weight  0.129547    EPangle 0.0116446   N_partons   183 |   N   pid status  E   Px  Py  Pz  Eta Phi
0   21  -1  0.332548    0.289347    -0.13353    -0.0950621  -0.294051   5.85082
1   21  1   4.45215 1.15158 -0.518765   -4.26926    -1.93227    5.85993
```
(with tabs as ">" for clarity):
```
#>Event>1>weight>0.129547>EPangle>0.0116446>N_partons>183>|>N>pid>status>E>Px>Py>Pz>Eta>Phi
```

### CODE REVIEW

**Comment by raymondEhlers** [comment]
@amitkr2410 and @jdmulligan The only changes from the other PR are to make this an "official" writer, including it in the master xml and moving the filename manipulation to `JetScape.cc` to match the other writers. I tested again after the changes and everything looks fine

**Comment by amitkr2410** [comment]
@raymondEhlers Tested the branch with few events. Looks good.

**Comment by raymondEhlers** [comment]
@amitkr2410 excellent, thanks!

**Comment by raymondEhlers** [comment]
Thanks for the comments! Apologies I couldn't attend - I had a conflict with today's meeting.

> Is it worth to explicitly print the version in the file/event header?

I assume you mean to write this in the format? I've been using the number of fields in the header as proxy, which has gotten me there so far, but I suppose that's not sustainable. If we make this change, it won't really match FinalState*, but I suppose that's fine. I can add this

> Some generators in the community use the "Oscar" format, see e.g. Oscar2013 here: http://theory.gsi.de/~smash/doc/1.6/format_oscar_particlelist.html. We could consider to use that format as well -- thoughts?

I'm not opposed to this in general, but such a change would be beyond the scope of these changes. From my perspective, these changes are strictly aimed towards supporting what is needed for the STAT calculations. From there, I did a bit of work to try to make them more generally useful, but unfortunately I can't afford to spend more time on this (since it would involve changes here, a v3 of the parser, propagating and validating all of the changes, etc). Perhaps this would be best served by a separate OSCAR writer?

**Comment by raymondEhlers** [comment]
Okay, I added an initial header line with versioning. Since we're having a proper header line, I also moved the definition of the columns to that line rather than repeating each event. The start of a file now looks like:

```
#>  JETSCAPE_FINAL_STATE>   v2> |>  N>  pid>status> E>  Px> Py> Pz
#>  Event>  1>  weight> 1>  EPangle>0>  N_hadrons>  188
0 211 0 96.4489 -1.15613 0.945563 96.4373
1 -211 0 257.128 -2.50664 4.03146 257.084
```

(I started at version 2 since that's practically where we're at at the moment)

**Comment by jdmulligan** [comment]
Hi @raymondEhlers,

Thanks! Yes, understood on the format front -- let's go ahead with this, and if interest we can always add/update OSCAR at a later time.

Thank you for the very nice feature!

I will merge to the release branch once the build test passes (requires music update open in other PR)

**Pull request merged**
