### PR TITLE
Fix vir_factor in PythiaGun

### PR DESCRIPTION
**Pull request by Hendrik1704**
This fixes a bug when a negative `vir_factor` is used in the PythiaGun. The other files are changed due to the updates on the main branch, where the branch is based.

### CODE REVIEW

**Comment by amajumder** [comment]
what is the problem that is being fixed?

**Review by latessa — APPROVED** [review]
Tests pass.  Looks good.  I will redirect this to a JETSCAPE-3.6.4-RC branch before merging since there are now multiple pull requests.  Is this PR also for X-SCAPE or only JETSCAPE?

**Comment by Hendrik1704** [comment]
This is also for X-SCAPE

**Comment by Hendrik1704** [comment]
I have implemented the flag we have discussed in the COMP meeting.

@latessa, @cparker24, @amajumder, @rjfries Please have a look at the changes with the new flag.

**Review by rjfries — APPROVED** [review]
Looking good to me

**Comment by cparker24** [comment]
I would make the epemGun Info statement more descriptive. For example "vir_factor set to use momentum, will not affect epemGun".  Something that makes it clear what the setting is and why it's being ignored, especially since the statement procs on the default settings.

**Review by latessa — APPROVED** [review]

**Comment by Hendrik1704** [comment]
@cparker24 I added your info statement to the code.

**Review by cparker24 — APPROVED** [review]

**Pull request merged**
