### PR TITLE
OpenMP ThermalPrnSampler with Counter-Based RNG

### PR DESCRIPTION
**Pull request by latessa**
This PR rewrites the omp_improved branch OpenMP implementation of ThermalPtnSampler with a new counter-based (Random123) RNG for faster performance.

[ThermalPtnPerformanceTimes.pdf](https://github.com/user-attachments/files/16683664/ThermalPtnPerformanceTimes.pdf)

This replaces PR #209, so I think PR #209 can be closed without merging (as it's included in the commit history here).

### CODE REVIEW

**Comment by Hendrik1704** [comment]
@latessa I tried to merge the last things from my branch into your branch. I faced the following problems:
- After fixing some merge conflicts, I wanted to run the unittests I had prepared on my branch. The test for the brick is failing with a segmentation fault. I think there are arguments for the RNG missing in the `SamplePartons` function. Please have a look at this.
- The other problem is that now with the new RNG the numbers of partons have changed, which also causes the other unit tests to fail. Do you have an idea how we can fix this? Should we just print the numbers once and then put them in the tests? Will they always be the same? I haven't checked that yet.
- It seems that the `std::mt19937_64` is still used in the code. Is this wanted?

**Comment by Hendrik1704** [comment]
Great, thanks!

OK, then we should update the numbers if they are reproducible.

I would say we should use the counter-based RNG everywhere in the class, especially if we want to implement this RNG for the whole framework at some point. What do you think?

**Comment by latessa** [comment]
- This PR update fixes the seg fault in brick.
- Counter-based randomization with Random123 is now implemented throughout the ThermPtnSampler class and all uses of state-based randomization are removed.
- The ThermPtnSampler unit tests were updated with the new expected results in consideration of the new randomization methods throughout.
- The ThermPtnSampler unit tests were added to the GitHub Actions automated workflows.
- Functionality was added to TEST_sample_2p1d and TEST_sample_3p1d  to verify that the results stay the same when when different numbers of threads are used.

**Review by Hendrik1704 — APPROVED** [review]
Looks good now. I have removed one last compiler warning `warn_unused_result` generated by one of the modified unit tests. Now it compiles without warnings.

**Pull request merged**
