### PR TITLE
Jetscape 3.6 rc

### PR DESCRIPTION
**Pull request by latessa**
This PR will merge the JETSCAPE-3.6-RC changes into main for the JETSCAPE-3.6 public release.  I will delay merging this PR and publishing the release to give collaborators a chance to respond to @jhputschke 's COMP channel post about whether we're expecting any additional PR's for the 3.6 release.  Thanks.

### CODE REVIEW

**Review by Hendrik1704 — APPROVED** [review]
Looks good.

I've tested the things where I was not involved, hydro and soft particlization improvements and they look fine. The new hydro beast mode is really nice.

**Review by LSchwiebert — APPROVED** [review]
Looks good to me.

**Comment by jhputschke** [comment]
Looks good to me, put before we merge, can we change in the README the version number to 3.6 ... With that we can merge and work on moving things in the XSCAPE repos too ... thanks @latessa in advance!

**Review by jhputschke — APPROVED** [review]
Looks good!

**Pull request merged**
