### PR TITLE
Fix typos in JetScape messages to address issue #120

### PR DESCRIPTION
**Pull request by LSchwiebert**
Minor corrections to various JetScape messages to address typos in the messages.

Also updated the sample test outputs, so that the results will still match once the PR is merged.

### CODE REVIEW

**Comment by LSchwiebert** [comment]
If it is not necessary to update the test files, then I will cancel this PR and generate a new PR that touches only a few source files.

**Comment by latessa** [comment]
Since output from the src files are used for comparison in the all those test folder files, matching test data _is_ likely needed.

How should we proceed with updates such as these?  For example, should we be working on a branch for a 3.5.1 release and redirecting pull requests to a 3.5.1-beta branch.  Or do pull requests such as this one get merged directly into main?  If so, does the JETSCAPE version number get updated?

**Comment by LSchwiebert** [comment]
That's a good point. We should create a release candidate for Jetscape 3.5.1 and the PR should be directed to that. I'll let you set that up according to whatever naming convention you want and then redo by PR.

There are a couple other patches that we need as well. One to change from using a 'Master' XML file to a 'Main' XML file. And another to patch the looping problem in Matter & LBT.

Once those patches are tested, we should create release 3.5.1. Unless there are additional issues identified, of course.

**Comment by latessa** [comment]
I've redirected and merged your PR to JETSCAPE-3.5.1-RC.

**Pull request merged**
