### PR TITLE
Particle writer

### PR DESCRIPTION
**Pull request by amajumder**
Pushing docker changes and hadron printer from Chuck to master

### CODE REVIEW

**Comment by amajumder** [comment]
@bardelch this seems to have issues downloading SMASH

**Comment by amajumder** [comment]
@bardelch Chuck!! are you noticing this?

**Comment by amajumder** [comment]
@jdmulligan , I am trying to find out how the online regression system is set up. It seems my recent pull request failed because it could not find pythia. Where is pythia supposed to be in the online regression system?

**Comment by bardelch** [comment]
So, this is pulling in a lot of backed up changes; dockerize, mine=generic, and particle writer.  Should we pull all this in or clear out previous pulls before this?

**Comment by amajumder** [comment]
There it is...  

-- ** WRONG Pythia version: 8.235, required 8.303.
-- Found Pythia: /usr/local/pythia8235/lib/libpythia8.a (Required is exact version "8.303")

**Comment by jdmulligan** [comment]
Hi @bardelch @amajumder ,

There is already a PR #65 with the docker changes that was already reviewed -- they should of course not both go in. So @bardelch I'll let you specify how to proceed (I would personally suggest to merge the already reviewed one, and then update this PR accordingly).

It seems the SMASH pythia version requirement has changed from 8.235 to 8.303 (https://github.com/smash-transport/smash). We will accordingly need to update the PYTHIA version in the base docker container -- I think it should be harmless to the rest of JETSCAPE. I'll take a look today.

**Comment by jdmulligan** [comment]
We should discuss changing the PYTHIA version at the next COMP meeting (see #74), but in the meantime, since the regression test passes in this PR, the failed build test is okay. 

So once @bardelch decides how to proceed with the multiple PRs, this can go ahead.

**Comment by jdmulligan** [comment]
Closing -- superseded by #80

**Pull request closed without merging**
