### PR TITLE
Bug fixes, C++17, softMomentumCutoff

### LINKED ISSUE #155: Reader getSigmaGen function returns 0
The getSigmaGen and getSigmaErr functions skip the first 2 words in the line and then set the sigma value equal to the 3rd. However, the line is "# JetScape writersigmaGen [value]" which means it will return writersigmaGen instead of the actual value. Adding a 3rd skip fixes the issue and returns the correct value.

### LINKED ISSUE #157: Bug in Matter virtuality computation logic
In `Matter.cc` there is an inconsistency in the while condition between the functions `generate_vac_t()` and `generate_vac_t_w_M()`:

https://github.com/JETSCAPE/JETSCAPE/blob/68a45ce4adaf900b3e5eb40f3c111d7b287a8017/src/jet/Matter.cc#L2009

https://github.com/JETSCAPE/JETSCAPE/blob/68a45ce4adaf900b3e5eb40f3c111d7b287a8017/src/jet/Matter.cc#L2163-L2171

Depending on the physics in the algorithm, either one of them is wrong. If the first one is correct, then the second one should have an `||` instead of an `&&`.
There might be other places in Matter, where there is an inconsistency in the while conditions.

### PR DESCRIPTION
**Pull request by Hendrik1704**
This PR fixes the bug in the Matter logic and closes #157. It introduces the `vir_factor` in the case of a negative parameter such that the parameter allows for a user handling of the maximum virtuality in this case.

The PR fixes the `sigmaGen` and `sigmaErr` reader and closes #155.

C++17 is now used to compile the code and the outdated `<useHybridHad>` flag is removed from all config files.

In the PythiaGun the xml parameters are moved to the init function and a new parameter `<softMomentumCutoff>` is introduced to handle the low momentum cutoff in the initial state. The default value is set such that the setup from the PP19 paper is implemented. In the case of a negative `vir_factor` the absolute three momentum is used to be consistent with the handling in the Matter module.

### CODE REVIEW

**Comment by jhputschke** [comment]
Looks good to me. @Hendrik1704 the failing of the tests is expected du to these changes, if so, please confirm. @latessa we then have to update the reference data ...

**Comment by latessa** [comment]
I'm working on the updated reference data now.  Once the tests pass and this PR is merged, I will also prepare the JETSCAPE 3.6 release (unless there's any other PR we're expecting).

Are we also ready to bring these JETSCAPE 3.6 changes to an X-SCAPE release candidate branch in X-SCAPE-COMP?

**Review by latessa — APPROVED** [review]
The tests are now passing with the updated reference data.  Looks good.

**Comment by Hendrik1704** [comment]
@jhputschke The failing tests were expected.

**Pull request merged**
