### PR TITLE
Few minor parameter fixes

### LINKED ISSUE #173: Thermal parton sampling creates nan values for 2+1D boost invariant case
During my recent comparison of colorless and hybrid hadronization I found that in the 2+1D boost invariant case the `ThermalPartonSampler` generates `nan` values for some partons while boosting them to the correct rapidity slice.
@rjfries and I found out that there was a change of some of the components of the four velocity missing when boosting the sampled partons to their corresponding pseudorapidity slice.
This bug leads then to a propagation of `nan` values into hybrid hadronization, such that most events can not be hadronized in this setup.

@rjfries and I have identified the missing pieces in the transformation, and I'm currently testing them. I'll post any updates here.

### PR DESCRIPTION
**Pull request by Hendrik1704**
This PR implements:
- `lambdaQCD` is now an XML parameter, with the default value taken from the former JetscapeConstants.h. This parameter is used in Bayesian analyses now.
- This fixes #173 in the thermal parton sampler.
- This makes the handling of the `eCMforHadronization` parameter consistent between the three hadronization methods. The input value is divided by 6 in all cases.
- There are more comments added in the main XML file, especially for the `vir_factor` and the hadronization section.

### CODE REVIEW

**Review by latessa — COMMENTED** [review]
Are these updates expected to change the pp and PbPb automated test output?  I ran the tests offline and the output doesn't match.  If this is expected, I can update the reference files with the output generated from this PR.

The automated tests are now turned on for the 3.6.1-RC branch.

**Comment by cparker24** [comment]
The parton propagation change to 0 will definitely affect vacuum runs but I'm not sure how much.

**Comment by latessa** [comment]
Any change will affect whether the tests succeed, so I'll go ahead and update the reference files with this new output.  Thanks.

**Review by cparker24 — COMMENTED** [review]
All changes look good to me.

**Review by latessa — APPROVED** [review]
Looks good to me too.  The automated test reference files have been updated using output generated with this PR.

**Pull request merged**
