### PR TITLE
Jetscape 3.6 can reproduce sims results.

### PR DESCRIPTION
**Pull request by xyw2016**
For this update, I have made the following modifications:

1. Added a new parameter tau_j in the freestream module.
2. Removed some unnecessary default parameters in iniSpectraSamplerWrapper.cc.
3. Added a user XML input file to reproduce sims results.

### CODE REVIEW

**Comment by chunshen1987** [comment]
The changes in the files look good to me.

**Review by jhputschke — APPROVED** [review]
Looks good to me too. @latessa, can we also propagate this in the XSCAPE branches accordingly. We could update to 3.6.1, however since there are actually no real changes in the code .. but maybe it is better to go to 3.6.1 ...

**Comment by latessa** [comment]
The PR looks good.

I know for the recent X-SCAPE release, we set some of the external packages get scripts to use specific commits from the external repositories.  Would it be a good idea to also use specific commits (such as this most recent [db32089](https://github.com/MUSIC-fluid/MUSIC/commit/db320898c4a9bd99ed21aa9dbb7c78e2cb0729bd)) for this next JETSCAPE release?  I'll ask about this at the COMP meeting.

**Review by latessa — APPROVED** [review]
Looks good.  I will redirect and merge this PR to a release candidate branch.

**Pull request merged**
