### PR TITLE
Updates for Hybrid Hadronization

### PR DESCRIPTION
**Pull request by mkordell**
This includes updates and bugfixes for Hybrid Hadronization.  This PR does not include any modifications to xml configs - that will be in a separate PR to minimize automated test breaking.

Recombination now respects color structure and creates new color structure as partons are recombined, that then gets used for string fragmentation.

Brick thermal parton sampling added - including a finite length brick for jet quenching & HH.

e+e- Gun included for running e+e- events.

### CODE REVIEW

**Comment by mkordell** [comment]
I think that one of the modifications to PythiaGun may have caused the regression test to still fail.  I can revert the changes and see if it passes if it will help?

**Comment by jdmulligan** [comment]
Hi @mkordell ,

Thanks a lot -- in general looks good to me. I was indeed wondering about some of the PythiaGun changes -- I think introducing the `softqcd` flag is no problem, but a couple things I was not sure about:

- Replacing diquarks with quarks -- this could cause a breaking change -- could you explain why it is needed, for my understanding?
- Setting the binary collision point -- this may break the tests in a trivial way
- Setting the parton color -- it seems this would always be done now regardless of hybridhadronization -- can this cause breaking changes, and if so, can you explain what the change is needed for?

Could I ask you to do one of the following?
(A) revert those specific changes until we can verify the tests pass (we can then add them back), or 
(B) compare a sample JETSCAPE output before and after the commit (with a fixed random seed), to verify whether you see exact agreement except related the three specific points above?

**Comment by mkordell** [comment]
Hi @jdmulligan,

Sure, I can revert those changes.

The thought for replacing diquarks with antiquarks was to preserve the color tags in the event (both carry anti-color charge), and the framework is not equipped to handle diquarks (HH can handle them, but I don't think matter can).  By swapping into antiquarks (& quarks for anti-diquarks) it preserves the initial color structure that pythia provides.

It used to be that having the color tags set in PythiaGun (and in PGun) would break colored hadronization (and the usehybridhad flag was introduced to prevent this), but that issue has been fixed for some time now (a check had been introduced into colored hadronization to detect and repair color structures with duplicate color tags).

I'm not sure about the binary collision point code - that wasn't something I had added.  I think that it may have been something that was changed at some point after the move from JETSCAPE-COMP?  I will go ahead and remove that.

**Comment by jdmulligan** [comment]
@mkordell one other note: the Pb-Pb test makes use of the brick (this config: https://github.com/jdmulligan/JETSCAPE-analysis/blob/master/test/PbPb/config/jetscape_user.xml), so depending on the parameters you use (I didn't check in detail) that could also break the test.

**Comment by mkordell** [comment]
@jdmulligan Thank you for letting me know!  I wasn't sure what change I had made was causing it to fail the PbPb test.  I will revert the brick and see if that fixes it.

**Pull request closed without merging**
