### PR TITLE
remove gtl binary_function & add macOS workflow

### PR DESCRIPTION
**Pull request by latessa**
This PR resolves the compilation issue when using Clang 16 by removing the binary_function inheritance in the GTL library.

GitHub Actions workflows are also added to test that JETSCAPE compiles on native Mac hardware.  Separate workflows use Clang 15 and Clang 16, so both compilers are verified.

https://github.com/JETSCAPE/JETSCAPE/actions/runs/11506333653

This test compiles JETSCAPE on native Mac runners with the external packages Music, iSS, Freestream, and Smash turned on.

runJetscape with [arXiv_1910.05481/jetscape_user_PP_1910.05481.xml](https://github.com/JETSCAPE/JETSCAPE/blob/main/config/publications_config/arXiv_1910.05481/jetscape_user_PP_1910.05481.xml) is then executed just to ensure that JETSCAPE runs and exits successfully.

Would it be preferred for the clang 16 GTL fix to be redirected to the JETSCAPE 4.0 release candidate, or would it be preferred for there to be a JETSCAPE 3.6.6 release?

### CODE REVIEW

**Comment by latessa** [comment]
Since there will now be a JETSCAPE 3.6.6 interim release, it was suggested to include the GTL changes in the new 3.6.6 release.  I am therefore reopening this PR.

**Comment by latessa** [comment]
I resolved an issue with home brew that wasn't happening before, but now it looks like a certain dependency requires "unlinking."  I'm not sure why this is needed now - maybe it's a bug in a recent homebrew update - but this change resolves the problem, and the native MacOS test is again passing.

**Review by Hendrik1704 — COMMENTED** [review]
The test seems to work, but I have absolutely no experience with macOS, so I can not really comment on this PR 😅

**Comment by jhputschke** [comment]
Looks good, we also don't use the Dijkstra algorithm in the framework, so not a crucial function.

**Review by jhputschke — APPROVED** [review]
Looks good.

**Pull request merged**
