### PR TITLE
S phenix

### PR DESCRIPTION
**Pull request by pinkenburg**
external_packages/trento does not compile when building against sources compiled with c++17. The use of the c++11 standard is hardcoded in its CMakeLists.txt. This PR lets the user override this by setting the usual
 -DCMAKE_CXX_STANDARD=17
while preserving c++11 as the default

### CODE REVIEW

**Comment by jhputschke** [comment]
Hi Chris,

thanks a lot for preparing the fix and PR!

Joern

**Review by jhputschke — APPROVED** [review]
Looks good, we should make sure to propagate this change also to the XSCAPE 1.1 release @latessa !

**Comment by latessa** [comment]
I've applied this change to the XSCAPE-1.1-RC branch.  

@jhputschke, should this PR be merged into main on its own as JETSCAPE 3.6.1 or held in a 3.6.1-RC to release along with any other forthcoming bug fixes?

**Comment by jhputschke** [comment]
@latessa I think since no source code was touched we can pull it into main and I don't think we have to create a new release tag.

**Review by latessa — APPROVED** [review]
Looks good.  Thanks.

**Pull request merged**
