### PR TITLE
Latessa/unit test action

### PR DESCRIPTION
**Pull request by latessa**
This PR adds a GitHub Actions workflow step to run the included unit tests on pushes and pull requests to main and 4.0 RC branch.  It also adds link in the README to a new wiki page with information about how to run and develop unit tests for JETSCAPE.

### CODE REVIEW

**Comment by latessa** [comment]
@Hendrik1704 Is the LiquifierBase unit test meant to run independently?  Or is it already a part of causal_liquifier?  When trying to run LiquifierBase independently, the test doesn't complete, and I get the following: 
` [Warning] void Jetscape::JetScapeXML::OpenXMLUserFile() : XML User file not found/not properly opened! Error code : 3`

**Review by Hendrik1704 — APPROVED** [review]
Looks good.

**Comment by Hendrik1704** [comment]
I think both of them should be able to run independently.

**Comment by Hendrik1704** [comment]
I think it's this line: https://github.com/JETSCAPE/JETSCAPE/blob/935b69291f0fd319f42dc6a9fb5960a4f814e16f/src/framework/LiquefierBase.cc#L93
causing trouble. I introduced this in the last version. I did not check the unit tests there. Now it can not find the values, since the test does not know about the XML file.

**Comment by latessa** [comment]
For now, I have not included the LiquifierBase test in the automated Actions workflow.  Should there be a solution to this before merging or do you prefer to keep the LiquifierBase test omitted from the automation?

**Comment by Hendrik1704** [comment]
I think we can neglect this test for the moment, but we should fix this at some point.

**Pull request merged**
