### PR TITLE
Bugfix: reset SMASH event index properly

### PR DESCRIPTION
**Pull request by doliinychenko**
For each hydro event there can be N sampler events. Particles from all N
sampler events are saved in a structure, which SMASH wrapper passes to SMASH.
Next hydro event executes new N sampler events and resets this structure, so
particles from previous hydro event are forgotten. SMASH wrapper didn't know
that and incremented the event number further instead of resetting it to 0 for
each new hydro event. That number was used as an array index, so for the second
hydro event it segfaulted.

This refs #55

Signed-off-by: Dmytro Oliinychenko <doliinychenko@lbl.gov>

### CODE REVIEW

**Comment by doliinychenko** [comment]
Another bug with SMASH wrapper was identified. New SMASH version needs explicit initialization of tabulated integrals from the wrapper, and it was not done, so SMASH crashed. The last commit fixes it.

**Comment by doliinychenko** [comment]
@jdmulligan Would it be possible to review and merge it?

**Comment by doliinychenko** [comment]
> Why did you not include the SMASH version here?

Because how? It's in a weird SMASH macro variable that I don't want to touch.

**Comment by vks** [comment]
@doliinychenko You could include `smash/config.h`, which is generated by CMake from `smash/config.h.in`. But this might interfere with JETSCAPE macros, so maybe it is not worth the trouble.

Just make sure that the tabulated integrals are not used for a different major SMASH version, because this might yield incorrect results.

**Comment by doliinychenko** [comment]
> @doliinychenko You could include `smash/config.h`, which is generated by CMake from `smash/config.h.in`. But this might interfere with JETSCAPE macros, so maybe it is not worth the trouble.
> 
> Just make sure that the tabulated integrals are not used for a different major SMASH version, because this might yield incorrect results.

It's a choice between risking to not update tabulations after smash version update and poisoning JETSCAPE with a macro called VERSION_MAJOR. Both are bad, but I think second is worse.

**Pull request merged**
